dependencies {
    api(platform(libs.http4k.bom))
    api(libs.http4k.ops.micrometer)
    api(libs.micrometer.registry.prometheus)
    api(projects.jsonSerializationCorrelationCore)
    api(libs.swissknife.http4k.server.utils)
    api(libs.swissknife.logger.core)
    api(libs.swissknife.configuration.utils)
    api(projects.correlationLoggingUtils)
    api(libs.swissknife.ddd.domain)
    api(libs.swissknife.service.readiness.http4k)
    api(libs.swissknife.web.api.domain)
    api(libs.swissknife.web.api.utils)

    implementation(libs.http4k.server.jetty)
    implementation(libs.guava)
    implementation(libs.swissknife.kotlin.extensions)
    implementation(libs.swissknife.lens.correlation.extensions)
    implementation(libs.swissknife.web.client.info.analyzer)
    implementation(projects.jsonSerializationWebApi)
    implementation(libs.swissknife.jwt.jose4j.processor)
    implementation(libs.swissknife.jwt.jose4j.issuer)
    implementation(libs.swissknife.jwt.jose4j.utils)
    implementation(projects.jwtDomain)

    testImplementation(libs.swissknife.web.api.test.utils)
    testImplementation(libs.swissknife.test.utils)
    testImplementation(projects.jwtTestUtils)
}
