dependencies {
    api(platform(libs.http4k.bom))
    api(libs.http4k.ops.micrometer)
    api(libs.micrometer.registry.prometheus)
    api(projects.pillarJsonSerializationCorrelationCore)
    api(projects.swissknifeHttp4kServerUtils)
    api(projects.swissknifeLoggerCore)
    api(projects.swissknifeConfigurationUtils)
    api(projects.pillarCorrelationLoggingUtils)
    api(projects.swissknifeDddDomain)
    api(projects.swissknifeServiceReadinessHttp4k)
    api(projects.swissknifeWebApiDomain)
    api(projects.swissknifeWebApiUtils)

    implementation(libs.http4k.server.jetty)
    implementation(libs.guava)
    implementation(projects.swissknifeKotlinExtensions)
    implementation(projects.swissknifeLensCorrelationExtensions)
    implementation(projects.swissknifeWebClientInfoAnalyzer)
    implementation(projects.pillarJsonSerializationWebApi)
    implementation(projects.swissknifeJwtJose4jProcessor)
    implementation(projects.swissknifeJwtJose4jIssuer)
    implementation(projects.swissknifeJwtJose4jUtils)
    implementation(projects.pillarJwtDomain)

    testImplementation(projects.swissknifeWebApiTestUtils)
    testImplementation(projects.swissknifeTestUtils)
    testImplementation(projects.pillarJwtTestUtils)
}
